// ace-server.cpp: HTTP server for ACE-Step music generation
//
// Single binary, three endpoints (POST /lm, POST /synth, POST /understand),
// one port. Models are discovered by scanning --models directory at startup
// (reads GGUF metadata only, no weights loaded).
//
// Each request loads the model, executes, and frees it. No model persists
// in VRAM between requests unless --keep-loaded is set. A single GPU mutex
// serializes access (503 if busy).
//
// Available models are classified by their GGUF general.architecture:
//   acestep-lm       -> lm bucket
//   acestep-dit      -> dit bucket
//   acestep-text-enc -> text-enc bucket (singleton, first entry used)
//   acestep-vae      -> vae bucket      (singleton, first entry used)
//
// Endpoint requirements:
//   /lm         LM
//   /synth      DiT + Text-Enc + VAE
//   /understand LM + DiT + VAE

#include "audio-io.h"
#include "model-registry.h"
#include "pipeline-lm.h"
#include "pipeline-synth.h"
#include "pipeline-understand.h"
#include "request.h"
#include "task-types.h"
#include "version.h"
#include "yyjson.h"

// embedded webui (generated by xxd.cmake from tools/webui/public/index.html.gz)
#include "index.html.gz.hpp"

// suppress warnings in third-party headers
#ifdef __GNUC__
#    pragma GCC diagnostic push
#    pragma GCC diagnostic ignored "-Wshadow"
#endif
#include "httplib.h"
#ifdef __GNUC__
#    pragma GCC diagnostic pop
#endif

#include <condition_variable>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <memory>
#include <mutex>
#include <random>
#include <string>
#include <thread>
#include <vector>

// RAII wrapper for C-allocated buffers (free() on destruction)
using unique_cfloat = std::unique_ptr<float, decltype(&free)>;
static unique_cfloat make_cfloat(float * p = nullptr) {
    return unique_cfloat(p, free);
}

#ifdef _WIN32
#    include <direct.h>
#    include <fcntl.h>
#    include <io.h>
#    include <windows.h>
#    include <sys/stat.h>
#    ifndef STDERR_FILENO
#        define STDERR_FILENO 2
#    endif
#else
#    include <dirent.h>
#    include <unistd.h>
#    include <sys/stat.h>
#    include <sys/types.h>
#endif

// portable fd wrappers. avoids macros that collide with C++ method names
// (e.g. sink.write() in httplib would be eaten by a write() macro).
#ifdef _WIN32
static int fd_pipe(int fd[2]) {
    return _pipe(fd, 4096, _O_BINARY);
}

static int fd_dup(int fd) {
    return _dup(fd);
}

static int fd_dup2(int src, int dst) {
    return _dup2(src, dst);
}

static int fd_read(int fd, void * buf, size_t n) {
    return _read(fd, buf, (unsigned) n);
}

static int fd_write(int fd, const void * buf, size_t n) {
    return _write(fd, buf, (unsigned) n);
}

static void fd_close(int fd) {
    _close(fd);
}
#else
static int fd_pipe(int fd[2]) {
    return pipe(fd);
}

static int fd_dup(int fd) {
    return dup(fd);
}

static int fd_dup2(int src, int dst) {
    return dup2(src, dst);
}

static int fd_read(int fd, void * buf, size_t n) {
    return (int) read(fd, buf, n);
}

static int fd_write(int fd, const void * buf, size_t n) {
    return (int) write(fd, buf, n);
}

static void fd_close(int fd) {
    close(fd);
}
#endif

// server instance pointer for the signal handler
static httplib::Server * g_svr = nullptr;

static void on_signal(int) {
    if (g_svr) {
        g_svr->stop();
    }
}

// single GPU mutex. httplib uses a thread pool, but only one request
// can use the GPU at a time. try_to_lock returns 503 if busy.
static std::mutex mtx_gpu;

// pipeline contexts. NULL when not loaded.
static AceLm *         g_ctx_lm         = nullptr;
static AceSynth *      g_ctx_synth      = nullptr;
static AceUnderstand * g_ctx_understand = nullptr;

// model registry (populated at startup from GGUF metadata)
static ModelRegistry g_registry;

// loaded model names (empty = nothing loaded)
static std::string g_loaded_lm;
static std::string g_loaded_dit;
static std::string g_loaded_lora;
static float       g_loaded_lora_scale = 1.0f;
static std::string g_loaded_und_dit;

// pipeline params (rebuilt from registry paths on each load)
static AceLmParams         g_lm_params;
static AceSynthParams      g_synth_params;
static AceUnderstandParams g_und_params;

// limits
static constexpr int MAX_SYNTH_BATCH = 9;

static int  g_max_batch   = 1;
static int  g_mp3_kbps    = 128;
static bool g_keep_loaded = false;

// output directory for saving generation metadata
static std::string g_output_dir;

// log capture: intercept stderr via pipe, forward to terminal + ring buffer.
// SSE clients connect to /logs and receive lines in real time.
#define LOG_RING_BITS 9
#define LOG_RING_SIZE (1 << LOG_RING_BITS)
#define LOG_RING_MASK (LOG_RING_SIZE - 1)

static std::mutex              mtx_log;
static std::condition_variable cv_log;
static std::string             log_ring[LOG_RING_SIZE];
static uint64_t                log_seq = 0;

static int g_real_stderr_fd = -1;
static int g_pipe_read_fd   = -1;

static void setup_log_capture() {
    g_real_stderr_fd = fd_dup(STDERR_FILENO);
    int pipefd[2];
    if (fd_pipe(pipefd) != 0) {
        g_real_stderr_fd = -1;
        return;
    }
    g_pipe_read_fd = pipefd[0];
    fd_dup2(pipefd[1], STDERR_FILENO);
    fd_close(pipefd[1]);
}

// reader thread: drain pipe, forward to real stderr, push lines to ring.
// exits when the write end of the pipe is closed (fd_dup2 restores real stderr).
static void log_reader_main() {
    char        buf[4096];
    std::string partial;
    for (;;) {
        int n = fd_read(g_pipe_read_fd, buf, sizeof(buf));
        if (n <= 0) {
            break;
        }
        fd_write(g_real_stderr_fd, buf, (size_t) n);
        partial.append(buf, (size_t) n);
        size_t pos;
        while ((pos = partial.find('\n')) != std::string::npos) {
            std::lock_guard<std::mutex> lock(mtx_log);
            log_ring[log_seq & LOG_RING_MASK] = partial.substr(0, pos);
            log_seq++;
            cv_log.notify_all();
            partial.erase(0, pos + 1);
        }
    }
    if (!partial.empty()) {
        std::lock_guard<std::mutex> lock(mtx_log);
        log_ring[log_seq & LOG_RING_MASK] = std::move(partial);
        log_seq++;
        cv_log.notify_all();
    }
    fd_close(g_pipe_read_fd);
}

static void teardown_log_capture() {
    if (g_real_stderr_fd < 0) {
        return;
    }
    fflush(stderr);
    fd_dup2(g_real_stderr_fd, STDERR_FILENO);
    // g_real_stderr_fd stays open: the reader thread writes to it
}

// RAII: captures stderr on construction, restores + joins reader on destruction.
// safe on any exit path (early arg errors, model load failures, normal shutdown).
struct LogCapture {
    std::thread reader;

    LogCapture() {
        setup_log_capture();
        reader = std::thread(log_reader_main);
    }

    ~LogCapture() {
        teardown_log_capture();
        cv_log.notify_all();
        if (reader.joinable()) {
            reader.join();
        }

        // reader is done draining the pipe, safe to close
        if (g_real_stderr_fd >= 0) {
            fd_close(g_real_stderr_fd);
            g_real_stderr_fd = -1;
        }
    }
};

// GET /logs: SSE stream of stderr lines.
// sends backlog (up to LOG_RING_SIZE) then streams new lines in real time.
static void handle_logs(const httplib::Request &, httplib::Response & res) {
    res.set_header("Cache-Control", "no-cache");
    res.set_header("X-Accel-Buffering", "no");
    res.set_chunked_content_provider(
        "text/event-stream", [cursor = uint64_t(0), init = false](size_t, httplib::DataSink & sink) mutable -> bool {
            std::unique_lock<std::mutex> lock(mtx_log);
            if (!init) {
                uint64_t avail = log_seq < LOG_RING_SIZE ? log_seq : (uint64_t) LOG_RING_SIZE;
                cursor         = log_seq - avail;
                while (cursor < log_seq) {
                    std::string ev = "data: " + log_ring[cursor & LOG_RING_MASK] + "\n\n";
                    cursor++;
                    lock.unlock();
                    if (!sink.write(ev.c_str(), ev.size())) {
                        return false;
                    }
                    lock.lock();
                }
                init = true;
            }
            cv_log.wait_for(lock, std::chrono::seconds(2));
            while (cursor < log_seq) {
                std::string ev = "data: " + log_ring[cursor & LOG_RING_MASK] + "\n\n";
                cursor++;
                lock.unlock();
                if (!sink.write(ev.c_str(), ev.size())) {
                    return false;
                }
                lock.lock();
            }
            return true;
        });
}

// cancel trampoline: bridges httplib's is_connection_closed to our cancel callback.
// data points to the std::function<bool()> from httplib::Request.
static bool server_cancel(void * data) {
    auto * fn = (const std::function<bool()> *) data;
    return (*fn)();
}

// helper: set a JSON error response
static void json_error(httplib::Response & res, int status, const char * msg) {
    yyjson_mut_doc * doc  = yyjson_mut_doc_new(NULL);
    yyjson_mut_val * root = yyjson_mut_obj(doc);
    yyjson_mut_doc_set_root(doc, root);
    yyjson_mut_obj_add_str(doc, root, "error", msg);
    char * json = yyjson_mut_write(doc, 0, NULL);
    yyjson_mut_doc_free(doc);
    res.status = status;
    res.set_content(json, "application/json");
    free(json);
}

// helper: 503 when GPU is busy
static void json_busy(httplib::Response & res) {
    res.status = 503;
    res.set_header("Retry-After", "5");
    res.set_content("{\"error\":\"Server busy\"}", "application/json");
}

// resolve model name: explicit request > already loaded > first in bucket
static std::string resolve_name(const std::vector<ModelEntry> & bucket,
                                const std::string &             requested,
                                const std::string &             loaded) {
    if (!requested.empty()) {
        return requested;
    }
    if (!loaded.empty()) {
        return loaded;
    }
    if (!bucket.empty()) {
        return bucket[0].name;
    }
    return "";
}

// server-side routing fields parsed from JSON (not part of AceRequest)
struct ServerFields {
    std::string synth_model;
    std::string lm_model;
    std::string lora;
    float       lora_scale;
};

static void parse_server_fields(const char * json, ServerFields * sf) {
    sf->synth_model = "";
    sf->lm_model    = "";
    sf->lora        = "";
    sf->lora_scale  = 1.0f;

    yyjson_doc * doc = yyjson_read(json, strlen(json), 0);
    if (!doc) {
        return;
    }
    yyjson_val * root = yyjson_doc_get_root(doc);
    if (!root) {
        yyjson_doc_free(doc);
        return;
    }

    // for arrays, take server fields from the first element
    yyjson_val * obj = root;
    if (yyjson_is_arr(root)) {
        obj = yyjson_arr_get_first(root);
    }
    if (!obj || !yyjson_is_obj(obj)) {
        yyjson_doc_free(doc);
        return;
    }

    yyjson_val * v;
    if ((v = yyjson_obj_get(obj, "synth_model")) && yyjson_is_str(v)) {
        sf->synth_model = yyjson_get_str(v);
    }
    if ((v = yyjson_obj_get(obj, "lm_model")) && yyjson_is_str(v)) {
        sf->lm_model = yyjson_get_str(v);
    }
    if ((v = yyjson_obj_get(obj, "lora")) && yyjson_is_str(v)) {
        sf->lora = yyjson_get_str(v);
    }
    if ((v = yyjson_obj_get(obj, "lora_scale")) && yyjson_is_num(v)) {
        sf->lora_scale = (float) yyjson_get_num(v);
    }

    yyjson_doc_free(doc);
}

// load LM. frees understand (shared pointers become invalid) but does not rebuild it.
// returns false on failure (caller returns 500).
static bool ensure_lm(const std::string & name) {
    if (g_ctx_lm && g_loaded_lm == name) {
        return true;
    }

    const ModelEntry * entry = registry_find(g_registry.lm, name.c_str());
    if (!entry) {
        fprintf(stderr, "[Server] LM not found: %s\n", name.c_str());
        return false;
    }

    // understand holds shared LM pointers, free before LM reload
    ace_understand_free(g_ctx_understand);
    g_ctx_understand = nullptr;
    g_loaded_und_dit.clear();
    ace_lm_free(g_ctx_lm);
    g_ctx_lm = nullptr;

    // load new
    fprintf(stderr, "[Server] Loading LM: %s\n", name.c_str());
    g_lm_params.model_path = entry->path.c_str();
    g_ctx_lm               = ace_lm_load(&g_lm_params);
    if (!g_ctx_lm) {
        fprintf(stderr, "[Server] FATAL: LM load failed\n");
        g_loaded_lm.clear();
        return false;
    }

    g_loaded_lm = name;
    return true;
}

// load understand pipeline (LM + tokenizer from DiT).
// reloads when LM or DiT changes. tokenizer weights differ between DiT variants.
static bool ensure_understand(const std::string & lm_name, const std::string & dit_name) {
    if (!ensure_lm(lm_name)) {
        return false;
    }

    // already loaded with the same DiT tokenizer
    if (g_ctx_understand && g_loaded_und_dit == dit_name) {
        return true;
    }

    // update dit_path for the tokenizer
    const ModelEntry * dit = registry_find(g_registry.dit, dit_name.c_str());
    if (dit) {
        g_und_params.dit_path = dit->path.c_str();
    }

    // (re)build understand with shared LM
    ace_understand_free(g_ctx_understand);
    g_ctx_understand = nullptr;

    g_und_params.shared_model = ace_lm_get_model(g_ctx_lm);
    g_und_params.shared_bpe   = ace_lm_get_bpe(g_ctx_lm);
    g_ctx_understand          = ace_understand_load(&g_und_params);
    if (!g_ctx_understand) {
        fprintf(stderr, "[Server] FATAL: understand load failed\n");
        g_loaded_und_dit.clear();
        return false;
    }

    g_loaded_und_dit = dit_name;
    return true;
}

// load synth pipeline (DiT + LoRA + text-enc + VAE). frees previous context first.
// returns false on failure (caller returns 500).
static bool ensure_synth(const std::string & dit_name, const std::string & lora_name, float lora_scale) {
    if (g_ctx_synth && g_loaded_dit == dit_name && g_loaded_lora == lora_name && g_loaded_lora_scale == lora_scale) {
        return true;
    }

    // need text-encoder + vae singletons
    if (g_registry.text_enc.empty() || g_registry.vae.empty()) {
        fprintf(stderr, "[Server] Missing Text-Enc or VAE in registry\n");
        return false;
    }

    const ModelEntry * dit = registry_find(g_registry.dit, dit_name.c_str());
    if (!dit) {
        fprintf(stderr, "[Server] DiT not found: %s\n", dit_name.c_str());
        return false;
    }

    // unload old
    ace_synth_free(g_ctx_synth);
    g_ctx_synth = nullptr;

    // set paths
    g_synth_params.text_encoder_path = g_registry.text_enc[0].path.c_str();
    g_synth_params.dit_path          = dit->path.c_str();
    g_synth_params.vae_path          = g_registry.vae[0].path.c_str();

    // resolve lora
    if (!lora_name.empty()) {
        const LoraEntry * lora = registry_find_lora(g_registry, lora_name.c_str());
        if (!lora) {
            fprintf(stderr, "[Server] LoRA not found: %s\n", lora_name.c_str());
            g_loaded_dit.clear();
            g_loaded_lora.clear();
            return false;
        }
        g_synth_params.lora_path  = lora->path.c_str();
        g_synth_params.lora_scale = lora_scale;
    } else {
        g_synth_params.lora_path  = nullptr;
        g_synth_params.lora_scale = 1.0f;
    }

    fprintf(stderr, "[Server] Loading synth: DiT=%s%s%s\n", dit_name.c_str(),
            lora_name.empty() ? "" : " LoRA=", lora_name.c_str());
    g_ctx_synth = ace_synth_load(&g_synth_params);
    if (!g_ctx_synth) {
        fprintf(stderr, "[Server] FATAL: synth load failed\n");
        g_loaded_dit.clear();
        g_loaded_lora.clear();
        return false;
    }

    g_loaded_dit        = dit_name;
    g_loaded_lora       = lora_name;
    g_loaded_lora_scale = lora_scale;
    return true;
}

// try to acquire GPU mutex. returns lock on success, empty lock on failure (sets 503).
static std::unique_lock<std::mutex> try_gpu_lock(httplib::Response & res) {
    std::unique_lock<std::mutex> lock(mtx_gpu, std::try_to_lock);
    if (!lock.owns_lock()) {
        json_busy(res);
    }
    return lock;
}

// conditionally unload LM pipeline (respects --keep-loaded)
static void maybe_unload_lm() {
    if (g_keep_loaded) {
        return;
    }
    ace_understand_free(g_ctx_understand);
    g_ctx_understand = nullptr;
    ace_lm_free(g_ctx_lm);
    g_ctx_lm = nullptr;
    g_loaded_lm.clear();
    g_loaded_und_dit.clear();
}

// conditionally unload synth pipeline (respects --keep-loaded)
static void maybe_unload_synth() {
    if (g_keep_loaded) {
        return;
    }
    ace_synth_free(g_ctx_synth);
    g_ctx_synth = nullptr;
    g_loaded_dit.clear();
    g_loaded_lora.clear();
}

// clamp value to [lo, hi]
static int clamp_int(int v, int lo, int hi) {
    return v < lo ? lo : (v > hi ? hi : v);
}

// generate a unique ID: YYYYMMDD-HHMMSS-XXXX (timestamp + 4 random hex chars)
static std::string generate_id() {
    char   buf[64];
    time_t now = time(nullptr);
    struct tm tm_buf;
#ifdef _WIN32
    localtime_s(&tm_buf, &now);
#else
    localtime_r(&now, &tm_buf);
#endif
    uint32_t r = std::random_device{}();
    snprintf(buf, sizeof(buf), "%04d%02d%02d-%02d%02d%02d-%04x", tm_buf.tm_year + 1900, tm_buf.tm_mon + 1,
             tm_buf.tm_mday, tm_buf.tm_hour, tm_buf.tm_min, tm_buf.tm_sec, r & 0xFFFF);
    return buf;
}

// build a generation JSON: AceRequest fields + generation_id + model routing info
static std::string build_generation_json(const AceRequest * r, const std::string & gen_id,
                                         const std::string & dit_name, const std::string & lm_name,
                                         const ServerFields & sf) {
    // start from sparse AceRequest JSON
    std::string base = request_to_json(r);
    yyjson_doc * doc  = yyjson_read(base.c_str(), base.size(), 0);
    yyjson_mut_doc * mdoc = yyjson_doc_mut_copy(doc, NULL);
    yyjson_doc_free(doc);
    yyjson_mut_val * root = yyjson_mut_doc_get_root(mdoc);

    // add generation metadata
    yyjson_mut_obj_add_str(mdoc, root, "generation_id", gen_id.c_str());

    // add resolved model names
    if (!dit_name.empty()) {
        yyjson_mut_obj_add_str(mdoc, root, "synth_model", dit_name.c_str());
    }
    if (!lm_name.empty()) {
        yyjson_mut_obj_add_str(mdoc, root, "lm_model", lm_name.c_str());
    }
    if (!sf.lora.empty()) {
        yyjson_mut_obj_add_str(mdoc, root, "lora", sf.lora.c_str());
        yyjson_mut_obj_add_real(mdoc, root, "lora_scale", sf.lora_scale);
    }

    yyjson_write_flag flags = YYJSON_WRITE_PRETTY | YYJSON_WRITE_PRETTY_TWO_SPACES | YYJSON_WRITE_FP_TO_FIXED(2);
    size_t len;
    char * json = yyjson_mut_write(mdoc, flags | YYJSON_WRITE_NEWLINE_AT_END, &len);
    yyjson_mut_doc_free(mdoc);
    std::string result(json, len);
    free(json);
    return result;
}

// ensure output directory exists
static void ensure_output_dir() {
#ifdef _WIN32
    _mkdir(g_output_dir.c_str());
#else
    mkdir(g_output_dir.c_str(), 0755);
#endif
}

// save generation: JSON metadata (with model info) + audio files to g_output_dir.
// expanded = one AceRequest per audio track (with resolved seeds).
static void save_generation(const std::string & gen_id, const std::vector<AceRequest> & expanded,
                            const std::string & dit_name, const std::string & lm_name,
                            const ServerFields & sf, const std::vector<std::string> & encoded, bool output_wav) {
    if (g_output_dir.empty() || expanded.empty()) {
        return;
    }
    ensure_output_dir();

    const char * ext = output_wav ? ".wav" : ".mp3";
    int          n   = (int) expanded.size();
    if ((int) encoded.size() < n) {
        n = (int) encoded.size();
    }

    for (int i = 0; i < n; i++) {
        // save JSON with generation_id and model info
        char path[512];
        snprintf(path, sizeof(path), "%s/%s_%d.json", g_output_dir.c_str(), gen_id.c_str(), i);
        std::string json = build_generation_json(&expanded[i], gen_id, dit_name, lm_name, sf);
        FILE * f = fopen(path, "w");
        if (f) {
            fwrite(json.data(), 1, json.size(), f);
            fclose(f);
            fprintf(stderr, "[Server] Saved metadata: %s\n", path);
        }

        // save audio
        if (!encoded[i].empty()) {
            snprintf(path, sizeof(path), "%s/%s_%d%s", g_output_dir.c_str(), gen_id.c_str(), i, ext);
            f = fopen(path, "wb");
            if (f) {
                fwrite(encoded[i].data(), 1, encoded[i].size(), f);
                fclose(f);
                fprintf(stderr, "[Server] Saved audio: %s\n", path);
            }
        }
    }
}

// encode audio tracks (normalize + MP3/WAV). frees AceAudio samples after encoding.
static std::vector<std::string> encode_audio(std::vector<AceAudio> & audio, int total_tracks, bool output_wav,
                                             const httplib::Request & req) {
    std::vector<std::string> encoded(total_tracks);
    for (int b = 0; b < total_tracks; b++) {
        if (!audio[b].samples) {
            continue;
        }
        audio_normalize(audio[b].samples, audio[b].n_samples * 2);
        if (output_wav) {
            encoded[b] = audio_encode_wav(audio[b].samples, audio[b].n_samples, 48000);
        } else {
            encoded[b] = audio_encode_mp3(audio[b].samples, audio[b].n_samples, 48000, g_mp3_kbps, server_cancel,
                                          (void *) &req.is_connection_closed);
        }
        ace_audio_free(&audio[b]);
    }
    return encoded;
}

// send encoded audio tracks as HTTP response (single or multipart/mixed)
static void send_audio_response(const std::vector<std::string> & encoded, bool output_wav,
                                httplib::Response & res) {
    const char * mime = output_wav ? "audio/wav" : "audio/mpeg";

    if ((int) encoded.size() == 1) {
        if (encoded[0].empty()) {
            json_error(res, 500, "Audio encoding failed");
            return;
        }
        res.set_content(encoded[0], mime);
        return;
    }

    // multiple tracks: multipart/mixed
    std::string boundary = "ace-batch-boundary";
    std::string body;
    for (const auto & e : encoded) {
        body += "--" + boundary + "\r\n";
        body += "Content-Type: ";
        body += mime;
        body += "\r\n\r\n";
        body += e;
        body += "\r\n";
    }
    body += "--" + boundary + "--\r\n";
    res.set_content(body, "multipart/mixed; boundary=" + boundary);
}

// POST /lm[?mode=inspire|format]
// accepts: AceRequest JSON (+ optional "lm_model" for LM selection)
// returns: JSON array of enriched AceRequests (lm_batch_size controls count)
// modes:
//   (none)    full: metadata + lyrics + audio codes
//   inspire   short caption -> metadata + lyrics (no codes)
//   format    caption + lyrics -> metadata + lyrics (no codes)
static void handle_lm(const httplib::Request & req, httplib::Response & res) {
    if (g_registry.lm.empty()) {
        json_error(res, 501, "No LM models in registry");
        return;
    }

    // parse mode from URL parameter
    int mode = LM_MODE_GENERATE;
    if (req.has_param("mode")) {
        std::string m = req.get_param_value("mode");
        if (m == "inspire") {
            mode = LM_MODE_INSPIRE;
        } else if (m == "format") {
            mode = LM_MODE_FORMAT;
        } else {
            json_error(res, 400, "Invalid mode (use: inspire, format)");
            return;
        }
    }

    // parse server fields + request
    ServerFields sf;
    parse_server_fields(req.body.c_str(), &sf);

    AceRequest ace_req;
    if (!request_parse_json(&ace_req, req.body.c_str())) {
        json_error(res, 400, "Invalid JSON");
        return;
    }
    if (ace_req.caption.empty()) {
        json_error(res, 400, "Caption is required");
        return;
    }

    int lm_batch_size = clamp_int(ace_req.lm_batch_size, 1, g_max_batch);

    auto lock = try_gpu_lock(res);
    if (!lock.owns_lock()) {
        return;
    }

    // load
    std::string lm_name = resolve_name(g_registry.lm, sf.lm_model, g_loaded_lm);
    if (!ensure_lm(lm_name)) {
        json_error(res, 500, "Failed to load LM");
        return;
    }

    // execute
    std::vector<AceRequest> out(lm_batch_size);
    int rc = ace_lm_generate(g_ctx_lm, &ace_req, lm_batch_size, out.data(), NULL, NULL, server_cancel,
                             (void *) &req.is_connection_closed, mode);

    maybe_unload_lm();
    lock.unlock();

    if (rc != 0) {
        json_error(res, 500, "LM generation failed");
        return;
    }

    // serialize output as a JSON array
    std::string body = "[";
    for (int i = 0; i < lm_batch_size; i++) {
        if (i > 0) {
            body += ",";
        }
        body += request_to_json(&out[i]);
    }
    body += "]";

    res.set_header("X-LM-Model", lm_name);
    res.set_content(body, "application/json");
}

// POST /synth[?wav=1]
// input:
//   application/json body        -> single request {} or batch [{req0}, {req1}, ...]
//   multipart/form-data          -> single request + audio file(s)
//     part "request":   JSON text
//     part "audio":     source audio (WAV or MP3)
//     part "ref_audio": timbre reference audio (WAV or MP3), optional
// output: audio/mpeg (default) or audio/wav (?wav=1)
//   batch == 1: raw audio body
//   batch >  1: multipart/mixed, each part is raw audio
// Batch size = number of JSON objects (after synth_batch_size expansion, clamped to 9).
// Metadata (seed, duration, etc) is already in the request JSON from /lm.
static void handle_synth(const httplib::Request & req, httplib::Response & res) {
    if (g_registry.dit.empty() || g_registry.text_enc.empty() || g_registry.vae.empty()) {
        json_error(res, 501, "No synth models in registry (need dit + text-encoder + vae)");
        return;
    }

    // parse server fields from JSON body (before multipart parsing)
    ServerFields sf;

    // parse request: plain JSON (single or array) or multipart (JSON + audio file)
    std::vector<AceRequest> ace_reqs;
    auto src_interleaved = make_cfloat();
    int  src_len         = 0;
    auto ref_interleaved = make_cfloat();
    int  ref_len         = 0;

    if (req.is_multipart_form_data()) {
        // multipart mode: single request + optional audio files
        AceRequest ace_req;

        std::string json_body;
        if (req.form.has_file("request")) {
            json_body = req.form.get_file("request").content;
        } else if (req.form.has_field("request")) {
            json_body = req.form.get_field("request");
        } else {
            json_error(res, 400, "Multipart: missing 'request' part");
            return;
        }
        parse_server_fields(json_body.c_str(), &sf);
        if (!request_parse_json(&ace_req, json_body.c_str())) {
            json_error(res, 400, "Multipart: invalid JSON in 'request' part");
            return;
        }

        if (req.form.has_file("audio")) {
            auto file = req.form.get_file("audio");
            if (file.content.empty()) {
                json_error(res, 400, "Multipart: empty 'audio' part");
                return;
            }
            int     T_audio = 0;
            float * planar  = audio_read_48k_buf((const uint8_t *) file.content.data(), file.content.size(), &T_audio);
            if (!planar || T_audio <= 0) {
                json_error(res, 400, "Failed to decode audio");
                return;
            }
            fprintf(stderr, "[Server] Source audio: %.2fs @ 48kHz\n", (float) T_audio / 48000.0f);
            src_interleaved.reset(audio_planar_to_interleaved(planar, T_audio));
            free(planar);
            src_len = T_audio;
        }

        if (req.form.has_file("ref_audio")) {
            auto file = req.form.get_file("ref_audio");
            if (!file.content.empty()) {
                int     T_audio = 0;
                float * planar =
                    audio_read_48k_buf((const uint8_t *) file.content.data(), file.content.size(), &T_audio);
                if (planar && T_audio > 0) {
                    fprintf(stderr, "[Server] Reference audio: %.2fs @ 48kHz\n", (float) T_audio / 48000.0f);
                    ref_interleaved.reset(audio_planar_to_interleaved(planar, T_audio));
                    free(planar);
                    ref_len = T_audio;
                } else {
                    fprintf(stderr, "[Server] WARNING: failed to decode ref_audio, ignoring\n");
                }
            }
        }
        ace_reqs.push_back(ace_req);
    } else {
        // plain JSON body: single object {} or array [{}, ...]
        parse_server_fields(req.body.c_str(), &sf);
        if (!request_parse_json_array(req.body.c_str(), &ace_reqs)) {
            json_error(res, 400, "Invalid JSON");
            return;
        }
    }

    if (ace_reqs.empty()) {
        json_error(res, 400, "Empty request");
        return;
    }
    if (ace_reqs[0].caption.empty() && ace_reqs[0].task_type != TASK_LEGO && ace_reqs[0].task_type != TASK_EXTRACT &&
        ace_reqs[0].task_type != TASK_COMPLETE) {
        json_error(res, 400, "Caption is required");
        return;
    }

    // expand synth_batch_size and process per-request groups.
    // each original request = one pipeline call (same codes = same T).
    // synth_batch_size variations within a group share the same T -> true GPU batch.
    // different requests can have different T (code length or duration) -> separate calls.
    // pre-compute total tracks across all groups
    int batch_n     = (int) ace_reqs.size();
    int total_alloc = 0;
    for (int ri = 0; ri < batch_n; ri++) {
        total_alloc += clamp_int(ace_reqs[ri].synth_batch_size, 1, MAX_SYNTH_BATCH);
    }
    std::vector<AceAudio> audio(total_alloc);
    int                   audio_idx = 0;

    auto lock = try_gpu_lock(res);
    if (!lock.owns_lock()) {
        return;
    }

    // load
    std::string dit_name = resolve_name(g_registry.dit, sf.synth_model, g_loaded_dit);
    if (!ensure_synth(dit_name, sf.lora, sf.lora_scale)) {
        json_error(res, 500, "Failed to load synth pipeline");
        return;
    }

    // expanded: one AceRequest per output track (with resolved seeds)
    std::vector<AceRequest> expanded;
    expanded.reserve(total_alloc);

    for (int ri = 0; ri < batch_n; ri++) {
        auto & r   = ace_reqs[ri];
        int    sbs = clamp_int(r.synth_batch_size, 1, MAX_SYNTH_BATCH);

        // resolve seed once per original request
        request_resolve_seed(&r);
        long long base_seed = r.seed;

        // build group: N copies of the same request with consecutive seeds
        std::vector<AceRequest> group(sbs);
        for (int i = 0; i < sbs; i++) {
            group[i]      = r;
            group[i].seed = base_seed + i;
        }

        std::vector<AceAudio> group_audio(sbs);
        int rc = ace_synth_generate(g_ctx_synth, group.data(), src_interleaved.get(), src_len, ref_interleaved.get(),
                                    ref_len, sbs, group_audio.data(), server_cancel,
                                    (void *) &req.is_connection_closed);

        if (rc != 0) {
            maybe_unload_synth();
            lock.unlock();
            for (int j = 0; j < audio_idx; j++) {
                ace_audio_free(&audio[j]);
            }
            for (int j = 0; j < sbs; j++) {
                ace_audio_free(&group_audio[j]);
            }
            json_error(res, 500, "Synth generation failed");
            return;
        }

        for (int i = 0; i < sbs; i++) {
            expanded.push_back(group[i]);
            audio[audio_idx++] = group_audio[i];
        }
    }

    maybe_unload_synth();
    lock.unlock();

    // generate unique ID, encode audio, save to disk, respond
    std::string gen_id     = generate_id();
    bool        output_wav = req.has_param("wav") && req.get_param_value("wav") == "1";
    auto        encoded    = encode_audio(audio, audio_idx, output_wav, req);

    save_generation(gen_id, expanded, dit_name, sf.lm_model, sf, encoded, output_wav);

    res.set_header("X-Generation-Id", gen_id);
    send_audio_response(encoded, output_wav, res);
}

// POST /understand
// Two modes:
//   multipart/form-data          -> full pipeline (audio + optional JSON params)
//     part "audio":   WAV or MP3 file (required)
//     part "request": JSON text (optional, for sampling params)
//   application/json body        -> codes-only (audio_codes in JSON, skip VAE+FSQ)
// returns: application/json AceRequest with metadata + lyrics + codes
static void handle_understand(const httplib::Request & req, httplib::Response & res) {
    if (g_registry.lm.empty() || g_registry.dit.empty() || g_registry.vae.empty()) {
        json_error(res, 501, "Understand requires LM, DiT and VAE models");
        return;
    }

    // parse request: multipart (audio + optional JSON) or plain JSON (codes-only)
    AceRequest ace_req;
    request_init(&ace_req);
    ace_req.lm_temperature = 0.3f;  // understand default: lower than generation
    ace_req.lm_top_p       = 1.0f;  // understand default: no nucleus sampling
    ServerFields sf;
    sf.synth_model = "";
    sf.lm_model    = "";
    sf.lora        = "";
    sf.lora_scale  = 1.0f;

    // parse server fields + request
    auto src_interleaved = make_cfloat();
    int  src_len         = 0;

    if (req.is_multipart_form_data()) {
        // multipart: required "audio" part, optional "request" part for sampling params
        // and server-side routing fields such as lm_model.
        if (req.form.has_file("request")) {
            const std::string & json = req.form.get_file("request").content;
            if (!request_parse_json(&ace_req, json.c_str())) {
                json_error(res, 400, "Multipart: invalid JSON in 'request' part");
                return;
            }
            parse_server_fields(json.c_str(), &sf);
        } else if (req.form.has_field("request")) {
            const std::string & json = req.form.get_field("request");
            if (!request_parse_json(&ace_req, json.c_str())) {
                json_error(res, 400, "Multipart: invalid JSON in 'request' part");
                return;
            }
            parse_server_fields(json.c_str(), &sf);
        }
        if (req.form.has_field("lm_model")) {
            sf.lm_model = req.form.get_field("lm_model");
        } else if (req.form.has_file("lm_model")) {
            sf.lm_model = req.form.get_file("lm_model").content;
        }

        if (!req.form.has_file("audio")) {
            json_error(res, 400, "Multipart: missing 'audio' part");
            return;
        }
        auto file = req.form.get_file("audio");
        if (file.content.empty()) {
            json_error(res, 400, "Multipart: empty 'audio' part");
            return;
        }

        // decode directly from multipart buffer (WAV/MP3 auto-detected)
        int     T_audio = 0;
        float * planar  = audio_read_48k_buf((const uint8_t *) file.content.data(), file.content.size(), &T_audio);
        if (!planar || T_audio <= 0) {
            json_error(res, 400, "Failed to decode audio");
            return;
        }

        fprintf(stderr, "[Server] Understand source: %.2fs @ 48kHz\n", (float) T_audio / 48000.0f);

        // convert planar [L:T][R:T] to interleaved [L0,R0,L1,R1,...] for pipeline
        src_interleaved.reset(audio_planar_to_interleaved(planar, T_audio));
        free(planar);
        src_len = T_audio;
    } else {
        // plain JSON body: codes-only mode
        parse_server_fields(req.body.c_str(), &sf);
        if (!request_parse_json(&ace_req, req.body.c_str())) {
            json_error(res, 400, "Invalid JSON");
            return;
        }
        parse_server_fields(req.body.c_str(), &sf);
    }

    auto lock = try_gpu_lock(res);
    if (!lock.owns_lock()) {
        return;
    }

    // load (LM + tokenizer from selected DiT)
    std::string lm_name  = resolve_name(g_registry.lm, sf.lm_model, g_loaded_lm);
    std::string dit_name = resolve_name(g_registry.dit, sf.synth_model, g_loaded_dit);
    fprintf(stderr, "[Server] Understand LM requested='%s' loaded='%s' resolved='%s'\n",
            sf.lm_model.c_str(), g_loaded_lm.c_str(), lm_name.c_str());
    if (!ensure_understand(lm_name, dit_name)) {
        json_error(res, 500, "Failed to load understand pipeline");
        return;
    }

    AceRequest out;
    int        rc = ace_understand_generate(g_ctx_understand, src_interleaved.get(), src_len, &ace_req, &out,
                                            server_cancel, (void *) &req.is_connection_closed);

    maybe_unload_lm();
    lock.unlock();

    if (rc != 0) {
        json_error(res, 500, "Understand generation failed");
        return;
    }

    res.set_header("X-LM-Model", lm_name);
    res.set_content(request_to_json(&out), "application/json");
}

// GET /props
// server configuration, available models, and default request.
// the webui reads this at boot to populate dropdowns and status indicators.
static void handle_props(const httplib::Request &, httplib::Response & res) {
    yyjson_mut_doc * doc  = yyjson_mut_doc_new(NULL);
    yyjson_mut_val * root = yyjson_mut_obj(doc);
    yyjson_mut_doc_set_root(doc, root);

    yyjson_mut_obj_add_str(doc, root, "version", ACE_VERSION);

    // helper: build a JSON array of model entry names
    auto add_names = [&](yyjson_mut_val * parent, const char * key, const std::vector<ModelEntry> & bucket) {
        yyjson_mut_val * arr = yyjson_mut_arr(doc);
        for (const auto & e : bucket) {
            yyjson_mut_arr_add_str(doc, arr, e.name.c_str());
        }
        yyjson_mut_obj_add_val(doc, parent, key, arr);
    };

    // models: available model names per bucket
    yyjson_mut_val * models = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_val(doc, root, "models", models);
    add_names(models, "lm", g_registry.lm);
    add_names(models, "embedding", g_registry.text_enc);
    add_names(models, "dit", g_registry.dit);
    add_names(models, "vae", g_registry.vae);

    // loras: available lora names
    yyjson_mut_val * loras_arr = yyjson_mut_arr(doc);
    for (const auto & e : g_registry.loras) {
        yyjson_mut_arr_add_str(doc, loras_arr, e.name.c_str());
    }
    yyjson_mut_obj_add_val(doc, root, "loras", loras_arr);

    // cli: server settings
    yyjson_mut_val * cli = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_val(doc, root, "cli", cli);
    yyjson_mut_obj_add_int(doc, cli, "max_batch", g_max_batch);
    yyjson_mut_obj_add_int(doc, cli, "mp3_bitrate", g_mp3_kbps);

    // default: full AceRequest with all defaults from request_init().
    // the webui reads this to populate LM placeholders.
    // DiT fields (inference_steps, guidance_scale, shift) are 0 = auto-detect;
    // their resolved placeholders come from presets below.
    AceRequest defaults;
    request_init(&defaults);
    std::string      defaults_str  = request_to_json(&defaults, false);
    yyjson_doc *     defaults_doc  = yyjson_read(defaults_str.c_str(), defaults_str.size(), 0);
    yyjson_mut_val * defaults_copy = yyjson_val_mut_copy(doc, yyjson_doc_get_root(defaults_doc));
    yyjson_mut_obj_add_val(doc, root, "default", defaults_copy);
    yyjson_doc_free(defaults_doc);

    // presets: auto-detect values for DiT sampling params.
    // the webui switches placeholders based on the selected DiT model.
    yyjson_mut_val * presets = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_val(doc, root, "presets", presets);

    yyjson_mut_val * turbo = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_int(doc, turbo, "inference_steps", 8);
    yyjson_mut_obj_add_real(doc, turbo, "guidance_scale", 1.0);
    yyjson_mut_obj_add_real(doc, turbo, "shift", 3.0);
    yyjson_mut_obj_add_val(doc, presets, "turbo", turbo);

    yyjson_mut_val * sft = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_int(doc, sft, "inference_steps", 50);
    yyjson_mut_obj_add_real(doc, sft, "guidance_scale", 1.0);
    yyjson_mut_obj_add_real(doc, sft, "shift", 1.0);
    yyjson_mut_obj_add_val(doc, presets, "sft", sft);

    // serialize
    yyjson_write_flag flags = YYJSON_WRITE_PRETTY | YYJSON_WRITE_PRETTY_TWO_SPACES | YYJSON_WRITE_FP_TO_FIXED(2);
    char *            json  = yyjson_mut_write(doc, flags, NULL);
    yyjson_mut_doc_free(doc);
    res.set_content(json, "application/json");
    free(json);
}

static void usage(const char * prog) {
    fprintf(stderr, "acestep.cpp %s\n\n", ACE_VERSION);
    fprintf(stderr,
            "Usage: %s --models <dir> [options]\n"
            "\n"
            "Required:\n"
            "  --models <dir>          Directory of GGUF model files\n"
            "\n"
            "LoRA:\n"
            "  --loras <dir>           Directory of LoRA adapters\n"
            "\n"
            "Memory control:\n"
            "  --keep-loaded           Keep models in VRAM between requests\n"
            "  --vae-chunk <N>         Latent frames per tile (default: 256)\n"
            "  --vae-overlap <N>       Overlap frames per side (default: 64)\n"
            "  --vae-cpu               Run VAE on CPU even when a GPU backend is active\n"
            "                          (faster on AMD iGPUs; DiT still runs on GPU)\n"
            "\n"
            "Output:\n"
            "  --mp3-bitrate <kbps>    MP3 bitrate (default: 128)\n"
            "  --output-dir <dir>      Save generation metadata JSON files\n"
            "\n"
            "Server:\n"
            "  --host <addr>           Listen address (default: 127.0.0.1)\n"
            "  --port <N>              Listen port (default: 8080)\n"
            "  --max-batch <N>         LM batch limit (default: 1)\n"
            "  --max-seq <N>           KV cache size (default: 8192)\n"
            "  --cors                  Enable CORS (Access-Control-Allow-Origin: *)\n"
            "\n"
            "Debug:\n"
            "  --no-fsm                Disable FSM constrained decoding\n"
            "  --no-fa                 Disable flash attention\n"
            "  --no-batch-cfg          Split CFG into two N=1 forwards\n"
            "  --clamp-fp16            Clamp hidden states to FP16 range\n",
            prog);
}

int main(int argc, char ** argv) {
    ace_lm_default_params(&g_lm_params);
    ace_synth_default_params(&g_synth_params);

    const char * host        = "127.0.0.1";
    int          port        = 8080;
    const char * models_dir  = nullptr;
    const char * loras_dir   = nullptr;
    bool         enable_cors = false;

    if (argc < 2) {
        usage(argv[0]);
        return 1;
    }

    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--models") && i + 1 < argc) {
            models_dir = argv[++i];
        } else if (!strcmp(argv[i], "--loras") && i + 1 < argc) {
            loras_dir = argv[++i];
        } else if (!strcmp(argv[i], "--max-seq") && i + 1 < argc) {
            g_lm_params.max_seq = atoi(argv[++i]);

            // vae tiling
        } else if (!strcmp(argv[i], "--vae-chunk") && i + 1 < argc) {
            g_synth_params.vae_chunk = atoi(argv[++i]);
        } else if (!strcmp(argv[i], "--vae-overlap") && i + 1 < argc) {
            g_synth_params.vae_overlap = atoi(argv[++i]);
        } else if (!strcmp(argv[i], "--vae-cpu")) {
            g_synth_params.vae_cpu = true;
        } else if (!strcmp(argv[i], "--keep-loaded")) {
            g_keep_loaded = true;

            // output
        } else if (!strcmp(argv[i], "--mp3-bitrate") && i + 1 < argc) {
            g_mp3_kbps = atoi(argv[++i]);

            // server
        } else if (!strcmp(argv[i], "--host") && i + 1 < argc) {
            host = argv[++i];
        } else if (!strcmp(argv[i], "--port") && i + 1 < argc) {
            port = atoi(argv[++i]);
        } else if (!strcmp(argv[i], "--max-batch") && i + 1 < argc) {
            g_max_batch = atoi(argv[++i]);

            // output
        } else if (!strcmp(argv[i], "--output-dir") && i + 1 < argc) {
            g_output_dir = argv[++i];

            // debug
        } else if (!strcmp(argv[i], "--no-fsm")) {
            g_lm_params.use_fsm = false;
        } else if (!strcmp(argv[i], "--no-fa")) {
            g_lm_params.use_fa    = false;
            g_synth_params.use_fa = false;
        } else if (!strcmp(argv[i], "--no-batch-cfg")) {
            g_lm_params.use_batch_cfg = false;
        } else if (!strcmp(argv[i], "--clamp-fp16")) {
            g_lm_params.clamp_fp16    = true;
            g_synth_params.clamp_fp16 = true;
        } else if (!strcmp(argv[i], "--cors")) {
            enable_cors = true;

        } else if (!strcmp(argv[i], "--help") || !strcmp(argv[i], "-h")) {
            usage(argv[0]);
            return 0;
        } else {
            fprintf(stderr, "Unknown option: %s\n", argv[i]);
            usage(argv[0]);
            return 1;
        }
    }

    // --models is required
    if (!models_dir) {
        fprintf(stderr, "[Server] ERROR: --models is required\n");
        usage(argv[0]);
        return 1;
    }

    // stderr capture for SSE /logs (must be after arg parsing so --help prints directly)
    LogCapture log_capture;

    // scan models directory (reads GGUF metadata only)
    fprintf(stderr, "[Server] Scanning models in %s\n", models_dir);
    if (!registry_scan(&g_registry, models_dir)) {
        fprintf(stderr, "[Server] ERROR: no GGUF models found in %s\n", models_dir);
        return 1;
    }

    // scan loras directory (optional)
    if (loras_dir) {
        fprintf(stderr, "[Server] Scanning LoRAs in %s\n", loras_dir);
        registry_scan_loras(&g_registry, loras_dir);
    }

    // validate pipeline
    bool have_lm    = !g_registry.lm.empty();
    bool have_dit   = !g_registry.dit.empty();
    bool have_enc   = !g_registry.text_enc.empty();
    bool have_vae   = !g_registry.vae.empty();
    bool have_synth = have_dit && have_enc && have_vae;

    // partial synth: some components found but pipeline incomplete
    if (!have_synth && (have_dit || have_enc || have_vae)) {
        char missing[64];
        int  n = 0;
        if (!have_dit) {
            n += snprintf(missing + n, sizeof(missing) - n, "%sDiT", n ? ", " : "");
        }
        if (!have_enc) {
            n += snprintf(missing + n, sizeof(missing) - n, "%sText-Enc", n ? ", " : "");
        }
        if (!have_vae) {
            n += snprintf(missing + n, sizeof(missing) - n, "%sVAE", n ? ", " : "");
        }
        if (have_lm) {
            fprintf(stderr, "[Server] WARNING: /synth unavailable, missing: %s\n", missing);
        } else {
            fprintf(stderr, "[Server] ERROR: no usable pipeline, synth missing: %s\n", missing);
            return 1;
        }
    }

    g_max_batch = clamp_int(g_max_batch, 1, MAX_SYNTH_BATCH);
    g_lm_params.max_batch = g_max_batch;

    // init understand params (vae for audio encoding, dit resolved per-request)
    ace_understand_default_params(&g_und_params);
    g_und_params.use_fa  = g_lm_params.use_fa;
    g_und_params.use_fsm = g_lm_params.use_fsm;
    if (have_vae) {
        g_und_params.vae_path = g_registry.vae[0].path.c_str();
    }

    bool have_understand = have_lm && have_dit && have_vae;

    // setup HTTP server
    httplib::Server svr;
    g_svr = &svr;

    // SO_REUSEADDR: allow rebind after TIME_WAIT (normal restart).
    // no SO_REUSEPORT: fail if another process is actively listening.
    svr.set_socket_options([](socket_t sock) {
        int one = 1;
#ifdef _WIN32
        setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, (const char *) &one, sizeof(one));
#else
        setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
#endif
    });

    // reject oversized bodies (256 MB: src + ref audio, up to 10min WAV each)
    svr.set_payload_max_length(256 * 1024 * 1024);

    // CORS: allow cross-origin requests when --cors is set
    if (enable_cors) {
        svr.set_default_headers({
            {"Access-Control-Allow-Origin",  "*"},
            {"Access-Control-Allow-Methods", "GET, POST, OPTIONS"},
            {"Access-Control-Allow-Headers", "Content-Type"},
        });
        svr.Options(".*", [](const httplib::Request &, httplib::Response & res) {
            res.status = 204;
        });
    }

    // all endpoints are always registered. handlers return 501 when the
    // backing pipeline has no models in the registry.
    svr.Post("/lm", handle_lm);
    svr.Post("/synth", handle_synth);
    svr.Post("/understand", handle_understand);
    svr.Get("/health", [&](const httplib::Request &, httplib::Response & res) {
        bool gpu_busy = !mtx_gpu.try_lock();
        if (!gpu_busy) {
            mtx_gpu.unlock();
        }

        yyjson_mut_doc * doc  = yyjson_mut_doc_new(NULL);
        yyjson_mut_val * root = yyjson_mut_obj(doc);
        yyjson_mut_doc_set_root(doc, root);
        yyjson_mut_obj_add_str(doc, root, "status", "ok");
        yyjson_mut_obj_add_bool(doc, root, "gpu_busy", gpu_busy);

        yyjson_mut_val * pipelines = yyjson_mut_obj(doc);
        yyjson_mut_obj_add_val(doc, root, "pipelines", pipelines);
        yyjson_mut_obj_add_bool(doc, pipelines, "lm", have_lm);
        yyjson_mut_obj_add_bool(doc, pipelines, "synth", have_synth);
        yyjson_mut_obj_add_bool(doc, pipelines, "understand", have_understand);

        char * json = yyjson_mut_write(doc, 0, NULL);
        yyjson_mut_doc_free(doc);
        res.set_content(json, "application/json");
        free(json);
    });
    svr.Get("/props", handle_props);
    svr.Get("/logs", handle_logs);
    
    // download saved JSON metadata files
    svr.Get("/json/:filename", [](const httplib::Request & req, httplib::Response & res) {
        if (g_output_dir.empty()) {
            json_error(res, 501, "JSON output not configured");
            return;
        }
        auto filename = req.path_params.at("filename");
        // security: only allow alphanumeric, underscore, dash, dot; reject path traversal
        if (filename.find("..") != std::string::npos) {
            json_error(res, 400, "Invalid filename");
            return;
        }
        for (auto c : filename) {
            if (!isalnum(c) && c != '_' && c != '-' && c != '.') {
                json_error(res, 400, "Invalid filename");
                return;
            }
        }
        std::string path = g_output_dir + "/" + filename;
        FILE * f = fopen(path.c_str(), "rb");
        if (!f) {
            json_error(res, 404, "File not found");
            return;
        }
        fseek(f, 0, SEEK_END);
        long size = ftell(f);
        fseek(f, 0, SEEK_SET);
        std::string content(size, 0);
        size_t nread = fread(content.data(), 1, size, f);
        fclose(f);
        if ((long) nread != size) {
            json_error(res, 500, "Failed to read file");
            return;
        }
        res.set_content(content, "application/json");
    });
    
    // list available JSON files
    svr.Get("/jsons", [](const httplib::Request &, httplib::Response & res) {
        if (g_output_dir.empty()) {
            res.set_content("[]", "application/json");
            return;
        }
        yyjson_mut_doc * doc = yyjson_mut_doc_new(NULL);
        yyjson_mut_val * root = yyjson_mut_arr(doc);
        yyjson_mut_doc_set_root(doc, root);
        
        #ifdef _WIN32
        WIN32_FIND_DATAA findData;
        HANDLE hFind = FindFirstFileA((g_output_dir + "/*.json").c_str(), &findData);
        if (hFind != INVALID_HANDLE_VALUE) {
            do {
                yyjson_mut_val * item = yyjson_mut_obj(doc);
                yyjson_mut_obj_add_str(doc, item, "filename", findData.cFileName);
                struct _stat64 st;
                std::string fullpath = g_output_dir + "/" + findData.cFileName;
                if (_stat64(fullpath.c_str(), &st) == 0) {
                    yyjson_mut_obj_add_int(doc, item, "size", st.st_size);
                    yyjson_mut_obj_add_int(doc, item, "mtime", st.st_mtime);
                }
                yyjson_mut_arr_append(root, item);
            } while (FindNextFileA(hFind, &findData));
            FindClose(hFind);
        }
        #else
        DIR * dir = opendir(g_output_dir.c_str());
        if (dir) {
            struct dirent * entry;
            while ((entry = readdir(dir)) != nullptr) {
                std::string name = entry->d_name;
                if (name.length() > 5 && name.substr(name.length() - 5) == ".json") {
                    yyjson_mut_val * item = yyjson_mut_obj(doc);
                    yyjson_mut_obj_add_str(doc, item, "filename", name.c_str());
                    struct stat st;
                    std::string fullpath = g_output_dir + "/" + name;
                    if (stat(fullpath.c_str(), &st) == 0) {
                        yyjson_mut_obj_add_int(doc, item, "size", st.st_size);
                        yyjson_mut_obj_add_int(doc, item, "mtime", st.st_mtime);
                    }
                    yyjson_mut_arr_append(root, item);
                }
            }
            closedir(dir);
        }
        #endif
        
        char * json = yyjson_mut_write(doc, 0, NULL);
        yyjson_mut_doc_free(doc);
        res.set_content(json, "application/json");
        free(json);
    });

    // embedded webui: gzipped single-page app (built by tools/webui/).
    // the browser decompresses transparently via Content-Encoding: gzip.
    // the .gz is committed to git so cloning + cmake + make gives a working UI.
    if (index_html_gz_len > 0) {
        svr.Get("/", [](const httplib::Request & req, httplib::Response & res) {
            if (req.get_header_value("Accept-Encoding").find("gzip") == std::string::npos) {
                res.set_content("Error: gzip is not supported by this browser", "text/plain");
            } else {
                res.set_header("Content-Encoding", "gzip");
                res.set_header("Cache-Control", "no-store, max-age=0");
                res.set_header("Pragma", "no-cache");
                res.set_content(reinterpret_cast<const char *>(index_html_gz), index_html_gz_len,
                                "text/html; charset=utf-8");
            }
        });
    }

    // graceful shutdown on SIGINT/SIGTERM
#ifdef _WIN32
    signal(SIGINT, on_signal);
    signal(SIGTERM, on_signal);
#else
    struct sigaction sa = {};
    sa.sa_handler       = on_signal;
    sigemptyset(&sa.sa_mask);
    sigaction(SIGINT, &sa, nullptr);
    sigaction(SIGTERM, &sa, nullptr);
#endif

    fprintf(stderr, "[Server] acestep.cpp %s\n", ACE_VERSION);
    fprintf(stderr, "[Server] Listening on %s:%d\n", host, port);
    fprintf(stderr, "[Server] Pipelines:%s%s%s\n", have_lm ? " /lm" : "", have_synth ? " /synth" : "",
            have_understand ? " /understand" : "");
    fprintf(stderr, "[Server] Models: %zu LM, %zu Text-Enc, %zu DiT, %zu VAE, %zu LoRA\n", g_registry.lm.size(),
            g_registry.text_enc.size(), g_registry.dit.size(), g_registry.vae.size(), g_registry.loras.size());
    if (!svr.listen(host, port)) {
        fprintf(stderr, "[Server] FATAL: cannot bind %s:%d\n", host, port);
    }

    // cleanup (all _free functions handle NULL)
    fprintf(stderr, "[Server] Shutting down...\n");
    ace_understand_free(g_ctx_understand);
    ace_synth_free(g_ctx_synth);
    ace_lm_free(g_ctx_lm);
    fprintf(stderr, "[Server] Done\n");

    return 0;
}
